/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dissys.chore;

/**
 *
 * @author Tsogzolmaa;
 */
public class ClientMainGuiController extends javax.swing.JFrame {

    /**
     * Creates new form ClientMainGuiController
     */
    public ClientMainGuiController() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SmartServices = new javax.swing.JTabbedPane();
        ChoreDivider = new javax.swing.JPanel();
        StartButtonChore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        FlightEmissionCalculator = new javax.swing.JPanel();
        StartButtonFlight = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        StoreMonitoring = new javax.swing.JPanel();
        StartButtonStore = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartButtonChore.setText("START SERVER");

        jLabel1.setText("ChoreDivider: Unary and Client streaming services");

        javax.swing.GroupLayout ChoreDividerLayout = new javax.swing.GroupLayout(ChoreDivider);
        ChoreDivider.setLayout(ChoreDividerLayout);
        ChoreDividerLayout.setHorizontalGroup(
            ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoreDividerLayout.createSequentialGroup()
                .addGroup(ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChoreDividerLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(StartButtonChore))
                    .addGroup(ChoreDividerLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel1)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        ChoreDividerLayout.setVerticalGroup(
            ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoreDividerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartButtonChore)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        SmartServices.addTab("Service-1", ChoreDivider);

        StartButtonFlight.setText("START SERVER");

        jLabel2.setText("FlightEmissionCalculator: Bi-directional service");

        javax.swing.GroupLayout FlightEmissionCalculatorLayout = new javax.swing.GroupLayout(FlightEmissionCalculator);
        FlightEmissionCalculator.setLayout(FlightEmissionCalculatorLayout);
        FlightEmissionCalculatorLayout.setHorizontalGroup(
            FlightEmissionCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                .addGroup(FlightEmissionCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(StartButtonFlight))
                    .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel2)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        FlightEmissionCalculatorLayout.setVerticalGroup(
            FlightEmissionCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartButtonFlight)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        SmartServices.addTab("Service-2", FlightEmissionCalculator);

        StartButtonStore.setText("START SERVER");

        jLabel3.setText("StoreMonitoring: Server streaming service");

        javax.swing.GroupLayout StoreMonitoringLayout = new javax.swing.GroupLayout(StoreMonitoring);
        StoreMonitoring.setLayout(StoreMonitoringLayout);
        StoreMonitoringLayout.setHorizontalGroup(
            StoreMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StoreMonitoringLayout.createSequentialGroup()
                .addGroup(StoreMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StoreMonitoringLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(StartButtonStore))
                    .addGroup(StoreMonitoringLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLabel3)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        StoreMonitoringLayout.setVerticalGroup(
            StoreMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StoreMonitoringLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartButtonStore)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        SmartServices.addTab("Service-3", StoreMonitoring);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(SmartServices, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(SmartServices, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientMainGuiController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChoreDivider;
    private javax.swing.JPanel FlightEmissionCalculator;
    private javax.swing.JTabbedPane SmartServices;
    private javax.swing.JButton StartButtonChore;
    private javax.swing.JButton StartButtonFlight;
    private javax.swing.JButton StartButtonStore;
    private javax.swing.JPanel StoreMonitoring;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
