package dissys.smartservices;


import grpc.generated.chore.ReportRequest;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tsogzolmaa;
 */
public class ChoreGui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public ChoreGui() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        NumPeopleLabel = new javax.swing.JLabel();
        numPeopleTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTextArea = new javax.swing.JTextArea();
        NumPeopleButton = new javax.swing.JButton();
        StartButtom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ReportButton = new javax.swing.JButton();
        resultLabel = new javax.swing.JLabel();
        CompletedTaskNumTextField = new javax.swing.JTextField();
        idlabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FinalReportButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumPeopleLabel.setText("Enter the number of people");

        numPeopleTextField.setText(" ");
        numPeopleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPeopleTextFieldActionPerformed(evt);
            }
        });

        serviceTextArea.setColumns(20);
        serviceTextArea.setRows(5);
        jScrollPane1.setViewportView(serviceTextArea);

        NumPeopleButton.setText("ENTER");
        NumPeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumPeopleButtonActionPerformed(evt);
            }
        });

        StartButtom.setText("START");
        StartButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtomActionPerformed(evt);
            }
        });

        jLabel1.setText("To get report click on GET REPORT button");

        ReportButton.setText("SEND");
        ReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportButtonActionPerformed(evt);
            }
        });

        resultLabel.setText("Result");

        CompletedTaskNumTextField.setText(" ");
        CompletedTaskNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompletedTaskNumTextFieldActionPerformed(evt);
            }
        });

        idlabel.setText("Enter ID of completed task one by one");

        jLabel2.setText("ID is between 1-11");

        FinalReportButton.setText("GET FINAL REPORT");
        FinalReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalReportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NumPeopleButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(numPeopleTextField)
                        .addComponent(NumPeopleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FinalReportButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(StartButtom)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idlabel)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(CompletedTaskNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(ReportButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(StartButtom)
                    .addComponent(idlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumPeopleLabel)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numPeopleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReportButton))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CompletedTaskNumTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NumPeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FinalReportButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numPeopleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPeopleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPeopleTextFieldActionPerformed

    private void NumPeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumPeopleButtonActionPerformed
        serviceTextArea.setText("");
        try { 
            //removed request building and calling stub and sending to server
            //instead calls requestChoreDivide method on client, so client will
            //send this request to server directly
            int numPeople = Integer.parseInt(numPeopleTextField.getText().trim());
            ChoreClient.requestChoreDivide(numPeople, serviceTextArea );
            }catch(Exception e){
        serviceTextArea.setText("Exception occured " + e.getMessage());
        }
    }//GEN-LAST:event_NumPeopleButtonActionPerformed

    private void StartButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtomActionPerformed
        //Starting new thread in the background to allow GUI performance.
        Thread serverThread = new Thread(new Runnable(){
            @Override
            public void run(){
            new ChoreServer().startServer();
            }
        });
        serverThread.start();
        serviceTextArea.setText("Server started.");
        //waiting briefly until server ready
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ChoreGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        serviceTextArea.append("\nDiscovering service...");
        try {
            //discover service from client
            ChoreClient.discoverAndStart(serviceTextArea);
            //serviceTextArea.setText(ChoreClient.message);
        } catch (IOException ex) {
            Logger.getLogger(ChoreGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(ChoreGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
     
        
    }//GEN-LAST:event_StartButtomActionPerformed

    private void ReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportButtonActionPerformed
        
        int completedTaskNum = Integer.parseInt(CompletedTaskNumTextField.getText().trim());
        ReportRequest request = ReportRequest.newBuilder().setCompletedTaskID(completedTaskNum).build();
        ChoreClient.requestObserver.onNext(request);
        serviceTextArea.setText("Request sent: completed task number " + completedTaskNum );
        
    
    }//GEN-LAST:event_ReportButtonActionPerformed

    private void CompletedTaskNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompletedTaskNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompletedTaskNumTextFieldActionPerformed

    private void FinalReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalReportButtonActionPerformed
        
        
        //here should call onCompleted() on request observer
        ChoreClient.requestObserver.onCompleted();
        
    }//GEN-LAST:event_FinalReportButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoreGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoreGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoreGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoreGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ChoreGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CompletedTaskNumTextField;
    private javax.swing.JButton FinalReportButton;
    private javax.swing.JButton NumPeopleButton;
    private javax.swing.JLabel NumPeopleLabel;
    private javax.swing.JButton ReportButton;
    private javax.swing.JButton StartButtom;
    private javax.swing.JLabel idlabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField numPeopleTextField;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JTextArea serviceTextArea;
    // End of variables declaration//GEN-END:variables
}
