package dissys.smartservices;

import grpc.generated.chore.ChoreRequest;
import grpc.generated.chore.ChoreResponse;
import grpc.generated.chore.ReportRequest;
import grpc.generated.chore.ReportResponse;
import grpc.generated.flight.CO2Request;
import grpc.generated.monitoring.MonitoringRequest;
import grpc.generated.monitoring.MonitoringResponse;
import io.grpc.StatusRuntimeException;
import io.grpc.stub.StreamObserver;
import java.io.IOException;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tsogzolmaa;
 */
public class ClientMainGuiController extends javax.swing.JFrame {

    /**
     * Creates new form ClientMainGuiController
     */
    public ClientMainGuiController() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SmartServices = new javax.swing.JTabbedPane();
        ChoreDivider = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTextArea = new javax.swing.JTextArea();
        NumPeopleLabel = new javax.swing.JLabel();
        numPeopleTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ReportButton = new javax.swing.JButton();
        ResultLabel = new javax.swing.JLabel();
        NumPeopleButton = new javax.swing.JButton();
        StartButtom = new javax.swing.JButton();
        FlightEmissionCalculator = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        service2TextArea = new javax.swing.JTextArea();
        ResultLabel1 = new javax.swing.JLabel();
        StartButton = new javax.swing.JButton();
        NextCityLabel = new javax.swing.JLabel();
        SupportedCityLabel = new javax.swing.JLabel();
        NextCityNameTextField = new javax.swing.JTextField();
        NextCityNameEnterButton = new javax.swing.JButton();
        CompletedButton = new javax.swing.JButton();
        StoreMonitoring = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        service3TextArea = new javax.swing.JTextArea();
        ResultLabel2 = new javax.swing.JLabel();
        StartButton1 = new javax.swing.JButton();
        SectionNameLabel = new javax.swing.JLabel();
        EnterButton = new javax.swing.JButton();
        SectionNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ChoreDivider: Unary and Client streaming services");

        serviceTextArea.setColumns(20);
        serviceTextArea.setRows(5);
        jScrollPane1.setViewportView(serviceTextArea);

        NumPeopleLabel.setText("Enter the number of people");

        numPeopleTextField.setText(" ");
        numPeopleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numPeopleTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("To get report click on GET REPORT button");

        ReportButton.setText("GET REPORT");
        ReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportButtonActionPerformed(evt);
            }
        });

        ResultLabel.setText("Output");

        NumPeopleButton.setText("ENTER");
        NumPeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumPeopleButtonActionPerformed(evt);
            }
        });

        StartButtom.setText("START SERVER");
        StartButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChoreDividerLayout = new javax.swing.GroupLayout(ChoreDivider);
        ChoreDivider.setLayout(ChoreDividerLayout);
        ChoreDividerLayout.setHorizontalGroup(
            ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChoreDividerLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChoreDividerLayout.createSequentialGroup()
                        .addComponent(NumPeopleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39))
                    .addGroup(ChoreDividerLayout.createSequentialGroup()
                        .addComponent(numPeopleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NumPeopleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(ReportButton)
                        .addGap(100, 100, 100))))
            .addGroup(ChoreDividerLayout.createSequentialGroup()
                .addGroup(ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(ChoreDividerLayout.createSequentialGroup()
                        .addGroup(ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ChoreDividerLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLabel1))
                            .addGroup(ChoreDividerLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ChoreDividerLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(StartButtom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ChoreDividerLayout.setVerticalGroup(
            ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoreDividerLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumPeopleLabel)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ChoreDividerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numPeopleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReportButton)
                    .addComponent(NumPeopleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(ResultLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SmartServices.addTab("Service-1", ChoreDivider);

        jLabel2.setText("FlightEmissionCalculator: Bi-directional service");

        service2TextArea.setColumns(20);
        service2TextArea.setRows(5);
        jScrollPane2.setViewportView(service2TextArea);

        ResultLabel1.setText("Output");

        StartButton.setText("START SERVER");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        NextCityLabel.setText("Enter city name to calculate flight emission");

        SupportedCityLabel.setText("Supported cities: Dublin, London, Tokyo, Paris");

        NextCityNameTextField.setText(" ");

        NextCityNameEnterButton.setText("ENTER");
        NextCityNameEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextCityNameEnterButtonActionPerformed(evt);
            }
        });

        CompletedButton.setText("SHUT DOWN CHANNEL");
        CompletedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompletedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FlightEmissionCalculatorLayout = new javax.swing.GroupLayout(FlightEmissionCalculator);
        FlightEmissionCalculator.setLayout(FlightEmissionCalculatorLayout);
        FlightEmissionCalculatorLayout.setHorizontalGroup(
            FlightEmissionCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                .addGroup(FlightEmissionCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                        .addGroup(FlightEmissionCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(jLabel2))
                            .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ResultLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(FlightEmissionCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NextCityLabel)
                                    .addComponent(SupportedCityLabel)))
                            .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NextCityNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NextCityNameEnterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(CompletedButton)
                .addGap(21, 21, 21))
        );
        FlightEmissionCalculatorLayout.setVerticalGroup(
            FlightEmissionCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlightEmissionCalculatorLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NextCityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SupportedCityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FlightEmissionCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextCityNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextCityNameEnterButton)
                    .addComponent(CompletedButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(ResultLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SmartServices.addTab("Service-2", FlightEmissionCalculator);

        jLabel3.setText("StoreMonitoring: Server streaming service");

        service3TextArea.setColumns(20);
        service3TextArea.setRows(5);
        jScrollPane3.setViewportView(service3TextArea);

        ResultLabel2.setText("Output");

        StartButton1.setText("START SERVER");
        StartButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButton1ActionPerformed(evt);
            }
        });

        SectionNameLabel.setText("Enter store section name to monitor");

        EnterButton.setText("ENTER");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        SectionNameTextField.setText(" ");
        SectionNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SectionNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StoreMonitoringLayout = new javax.swing.GroupLayout(StoreMonitoring);
        StoreMonitoring.setLayout(StoreMonitoringLayout);
        StoreMonitoringLayout.setHorizontalGroup(
            StoreMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StoreMonitoringLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(StartButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(StoreMonitoringLayout.createSequentialGroup()
                .addGroup(StoreMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StoreMonitoringLayout.createSequentialGroup()
                        .addGroup(StoreMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StoreMonitoringLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel3))
                            .addGroup(StoreMonitoringLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ResultLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(StoreMonitoringLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(SectionNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(StoreMonitoringLayout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(SectionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EnterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(275, 275, 275))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        StoreMonitoringLayout.setVerticalGroup(
            StoreMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StoreMonitoringLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StartButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SectionNameLabel)
                .addGap(18, 18, 18)
                .addGroup(StoreMonitoringLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnterButton)
                    .addComponent(SectionNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(ResultLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SmartServices.addTab("Service-3", StoreMonitoring);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(SmartServices, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(SmartServices, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numPeopleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numPeopleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numPeopleTextFieldActionPerformed

    private void ReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportButtonActionPerformed

        StreamObserver<ReportResponse> responseObserver =
        new StreamObserver<ReportResponse>(){
            @Override
            public void onNext(ReportResponse v) {
                serviceTextArea.setText("Response from server (Client streaming, Chore Report): " + v.getReportResult());
            }
            @Override
            public void onError(Throwable thrwbl) {
                serviceTextArea.setText("Error occurred during stream: " + thrwbl.getMessage());
                thrwbl.printStackTrace();
            }

            @Override
            public void onCompleted() {
                serviceTextArea.append("\n" + LocalTime.now().toString() + "\nReport is completed");
            }
        };
        //for request we have requestObserver on Server, so whenever client send request
        //using onNext, server can catch several requests and possible store them.
        //for this doChoreReport service, assynchronous stub is used because, we are sending
        //stream of request to server.
        //here using stub, method doChoreReport is triggered and responseObserver which
        //we defined its behaviour in this client class is sent to server as a parameter.
        StreamObserver<ReportRequest> requestObserver = ChoreClient
        .stubAsync
        .doChoreReport(responseObserver);

        try{
            requestObserver.onNext(ReportRequest.newBuilder().setCompletedTaskNum(11).build());
            Thread.sleep(500);
            requestObserver.onNext(ReportRequest.newBuilder().setCompletedTaskNum(1).build());
            Thread.sleep(500);
            requestObserver.onNext(ReportRequest.newBuilder().setCompletedTaskNum(6).build());
            Thread.sleep(500);
            requestObserver.onNext(ReportRequest.newBuilder().setCompletedTaskNum(3).build());
            Thread.sleep(500);
            requestObserver.onNext(ReportRequest.newBuilder().setCompletedTaskNum(4).build());
            Thread.sleep(500);

            requestObserver.onCompleted();

            //            Thread.sleep(10000);

        }catch(InterruptedException e){
            serviceTextArea.setText("Exception: " + e.getMessage());
        }
    }//GEN-LAST:event_ReportButtonActionPerformed

    private void NumPeopleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumPeopleButtonActionPerformed
        try {
            int numPeople = Integer.parseInt(numPeopleTextField.getText().trim());

            ChoreRequest request = ChoreRequest.newBuilder().setNumPeople(numPeople).build();

            ChoreResponse response = ChoreClient.stub.doChoderDivide(request);

            serviceTextArea.setText("Response from server " + response.getChoreResult());
        }catch(Exception e){
            serviceTextArea.setText("Exception occured " + e.getMessage());
        }
    }//GEN-LAST:event_NumPeopleButtonActionPerformed

    private void StartButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtomActionPerformed
        //Starting new thread in the background to allow GUI performance.
        Thread serverThread = new Thread(new Runnable(){
            @Override
            public void run(){
                new ChoreServer().startServer();
            }
        });
        serverThread.start();
        serviceTextArea.setText("Server started.");
        //waiting briefly until server ready
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(ChoreGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        serviceTextArea.append("\nDiscovering service...");
        try {
            //discover service from client
            ChoreClient.discoverAndStart(serviceTextArea);
            //serviceTextArea.setText(ChoreClient.message);
        } catch (IOException ex) {
            Logger.getLogger(ChoreGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(ChoreGui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_StartButtomActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        //Starting new thread in the background to allow GUI performance.
        Thread serverThread = new Thread(new Runnable(){
            @Override
            public void run(){
                new FlightServer().startServer();
            }
        });
        serverThread.start();
        service2TextArea.setText("Server started.");
        //waiting briefly until server ready
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(FlightGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        service2TextArea.append("\nDiscovering service...");
        try {
            //discover service from client
            FlightClient.discoverAndStart(service2TextArea);
            //serviceTextArea.setText(ChoreClient.message);
        } catch (IOException ex) {
            Logger.getLogger(FlightGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(FlightGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void NextCityNameEnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextCityNameEnterButtonActionPerformed

        //ArrayList<String> supportedCityNames = new ArrayList<>();
        String nextCity = NextCityNameTextField.getText().trim();
        try{
            CO2Request request = CO2Request.newBuilder().setNextCity(nextCity).build();
            //requestObserver 
            FlightClient.requestObserver.onNext(request);
            Thread.sleep(1500);

        }catch(InterruptedException e)
        {
            service2TextArea.setText("Exception occured " + e.getMessage());
        }

    }//GEN-LAST:event_NextCityNameEnterButtonActionPerformed

    private void CompletedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompletedButtonActionPerformed

        FlightClient.requestObserver.onCompleted();
    }//GEN-LAST:event_CompletedButtonActionPerformed

    private void StartButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButton1ActionPerformed
        //Starting new thread in the background to allow GUI performance.
        Thread serverThread = new Thread(new Runnable(){
            @Override
            public void run(){
                new StoreMonitoringServer().startServer();
            }
        });
        serverThread.start();
        service3TextArea.setText("Server started.");
        //waiting briefly until server ready
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(StoreGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        service3TextArea.append("\nDiscovering service...");
        try {
            //discover service from client
            StoreMonitoringClient.discoverAndStart(service3TextArea);
            //serviceTextArea.setText(ChoreClient.message);
        } catch (IOException ex) {
            Logger.getLogger(StoreGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(StoreGui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_StartButton1ActionPerformed

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed

        String sectionName = SectionNameTextField.getText().trim();
        service3TextArea.setText("" );
        try{
            MonitoringRequest request = MonitoringRequest
            .newBuilder().setSectionName(sectionName).build();

            StreamObserver<MonitoringResponse> responseObserver= new StreamObserver<MonitoringResponse>(){

                ArrayList<String> responseArray = new ArrayList<>();
                @Override
                public void onNext(MonitoringResponse v) {
                    service3TextArea.append("Response from server " );
                    service3TextArea.append(v.getStockLevelMessage());
                    responseArray.add(v.getStockLevelMessage());
                }

                @Override
                public void onError(Throwable thrwbl) {
                    service3TextArea.setText("Error occurred during stream: " + thrwbl.getMessage());
                    thrwbl.printStackTrace();             }

                @Override
                public void onCompleted() {
                    service3TextArea.append("\nServer response(s) completed");
                    service3TextArea.append("\nRecieved response(s) : " + responseArray.toString());
                }

            };

            StoreMonitoringClient.stubAsync.doMonitoring(request, responseObserver);

        }catch (StatusRuntimeException e) {
            e.getStatus();
        } 
    //commented out to keep server alive    
//        finally {
//            try {
//                StoreMonitoringClient.channel.shutdown().awaitTermination(5, TimeUnit.SECONDS);
//            } catch (InterruptedException ex) {
//                Logger.getLogger(ClientMainGuiController.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }

    }//GEN-LAST:event_EnterButtonActionPerformed

    private void SectionNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SectionNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SectionNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientMainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientMainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientMainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientMainGuiController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientMainGuiController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChoreDivider;
    private javax.swing.JButton CompletedButton;
    private javax.swing.JButton EnterButton;
    private javax.swing.JPanel FlightEmissionCalculator;
    private javax.swing.JLabel NextCityLabel;
    private javax.swing.JButton NextCityNameEnterButton;
    private javax.swing.JTextField NextCityNameTextField;
    private javax.swing.JButton NumPeopleButton;
    private javax.swing.JLabel NumPeopleLabel;
    private javax.swing.JButton ReportButton;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JLabel ResultLabel1;
    private javax.swing.JLabel ResultLabel2;
    private javax.swing.JLabel SectionNameLabel;
    private javax.swing.JTextField SectionNameTextField;
    private javax.swing.JTabbedPane SmartServices;
    private javax.swing.JButton StartButtom;
    private javax.swing.JButton StartButton;
    private javax.swing.JButton StartButton1;
    private javax.swing.JPanel StoreMonitoring;
    private javax.swing.JLabel SupportedCityLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField numPeopleTextField;
    private javax.swing.JTextArea service2TextArea;
    private javax.swing.JTextArea service3TextArea;
    private javax.swing.JTextArea serviceTextArea;
    // End of variables declaration//GEN-END:variables
}
