/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dissys.smartservices;


import grpc.generated.flight.CO2Request;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tsogzolmaa;
 */
public class FlightGui extends javax.swing.JFrame {

    /**
     * Creates new form FlightGui
     */
    public FlightGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartButton = new javax.swing.JButton();
        NextCityLabel = new javax.swing.JLabel();
        NextCityNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        serviceTextArea = new javax.swing.JTextArea();
        ResultLabel = new javax.swing.JLabel();
        NextCityNameEnterButton = new javax.swing.JButton();
        CompletedButton = new javax.swing.JButton();
        SupportedCityLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StartButton.setText("START");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        NextCityLabel.setText("Enter city name to calculate flight emission");

        NextCityNameTextField.setText(" ");

        serviceTextArea.setColumns(20);
        serviceTextArea.setRows(5);
        jScrollPane1.setViewportView(serviceTextArea);

        ResultLabel.setText("Result");

        NextCityNameEnterButton.setText("ENTER");
        NextCityNameEnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextCityNameEnterButtonActionPerformed(evt);
            }
        });

        CompletedButton.setText("COMPLETED");
        CompletedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompletedButtonActionPerformed(evt);
            }
        });

        SupportedCityLabel.setText("Supported cities: Dublin, London, Tokyo, Paris");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NextCityLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ResultLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NextCityNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(NextCityNameEnterButton))
                            .addComponent(SupportedCityLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(CompletedButton)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(NextCityLabel)
                .addGap(5, 5, 5)
                .addComponent(SupportedCityLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextCityNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextCityNameEnterButton))
                .addGap(35, 35, 35)
                .addComponent(CompletedButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResultLabel)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        //Starting new thread in the background to allow GUI performance.
        Thread serverThread = new Thread(new Runnable(){
            @Override
            public void run(){
                try {
                    new FlightServer().startServer();
                } catch (Exception ex) {
                    Logger.getLogger(FlightGui.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        serverThread.start();
        serviceTextArea.setText("Server started.");
        //waiting briefly until server ready
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(FlightGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        serviceTextArea.append("\nDiscovering service...");
        try {
            //discover service from client
            FlightClient.discoverAndStart(serviceTextArea);
            //serviceTextArea.setText(ChoreClient.message);
        } catch (IOException ex) {
            Logger.getLogger(FlightGui.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(FlightGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void NextCityNameEnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextCityNameEnterButtonActionPerformed
        
        //ArrayList<String> supportedCityNames = new ArrayList<>();
        String nextCity = NextCityNameTextField.getText().trim();
        try{
            
            CO2Request request = CO2Request.newBuilder().setNextCity(nextCity).build();
            
            FlightClient.requestObserver.onNext(request);
            Thread.sleep(1500);
        
        }catch(InterruptedException e)
        {
        serviceTextArea.setText("Exception occured " + e.getMessage());
        }
        
    }//GEN-LAST:event_NextCityNameEnterButtonActionPerformed

    private void CompletedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompletedButtonActionPerformed
        
        //FlightClient.requestObserver.onCompleted();
    }//GEN-LAST:event_CompletedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CompletedButton;
    private javax.swing.JLabel NextCityLabel;
    private javax.swing.JButton NextCityNameEnterButton;
    private javax.swing.JTextField NextCityNameTextField;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel SupportedCityLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea serviceTextArea;
    // End of variables declaration//GEN-END:variables
}
